services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  hw1:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Homework1:/usr/local/apache2/htdocs

  hw2:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./Homework2:/usr/local/apache2/htdocs
  
  hw3:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./Homework3/Dockerfile
    volumes:
      - ./Homework3/static:/app/static
      - ./Homework3/server.js:/app/server.js
      